name: Build Container CI

on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
         path: target/
  
  containerize:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          path: target/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: target/
      - name: Build container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ steps.extract_branch.outputs.branch }}
      - name: Build container Release (latest)
        id: docker_build_release
        uses: docker/build-push-action@v2
        if: steps.extract_branch.outputs.branch == 'master'
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:latest
